
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: {{ .Values.postgresql.replicaCount }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      hostname: postgres-container
      containers:
      - name: postgres
        image: {{ .Values.postgresql.image }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.env.POSTGRES_USER }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgresql.env.POSTGRES_PASSWORD }}
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.env.POSTGRES_DB }}
        ports:
        - containerPort: {{ .Values.postgresql.port }}
        volumeMounts:
        - name: postgres-pv
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-pv
        persistentVolumeClaim:
          claimName: postgres-pvc
